title: My Blog
author: mlow369
email: dontwanttoprovide@domain.com
description: > # this means to ignore newlines until "baseurl:"
 This is an experimental blog. For training purposes only
theme: minima
# social links
twitter_username: mikelows # DO NOT include the @ character, or else the build will fail!
github_username:  mlow369 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
